version: 2.1
jobs:
  build:
    docker:
      - image: dimtass/stm32-cde-image:latest
    steps:
      - checkout
      - run:
          name: Build firmware
          command: |
            git submodule sync
            git submodule update --init --recursive
            CLEANBUILD=true SRC=src_hal ./build.sh